[package]
name = "multiplatform"
version = "0.1.0"
edition = "2021"

[dependencies]
framework = { path = "../.." }
anyhow = "1"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
log = "0.4"

# necessary for wasm builds
[lib]
crate-type = ["cdylib", "rlib"]
